version: 0.0
os: linux
file:
  - source: /
    destination: /home/ec2-user/video_recommendations_app
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
