name: Describing Cities Server

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: ACR Login
        uses: azure/docker-login@v1
        with:
          login-server: cyfvideos.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build . -t cyfvideos.azurecr.io/video-recommendations
          docker push cyfvideos.azurecr.io/video-recommendations

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v3
      - name: Get IP
        id: ip
        uses: haythem/public-ip@v1.3
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Add IP to Azure
        run: az network nsg rule create --nsg-name ${{ secrets.AZURE_NSG }} --name GitHub-Actions --priority 300 -g ${{ secrets.AZURE_RG }} --destination-address-prefixes '*' --destination-port-ranges 22 --direction Inbound --source-address-prefixes ${{ steps.ip.outputs.ipv4 }} --description "Transfer files"
      - name: Docker run
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 300s
          script: bash videos.sh
      - name: Remove IP from Azure
        if: always()
        run: az network nsg rule delete -g ${{ secrets.AZURE_RG }} --nsg-name ${{ secrets.AZURE_NSG }} -n GitHub-Actions
